"""Deterministic plant geometry core for FSPM groundwork."""

from __future__ import annotations

from rad_rebuild.radiance.engine.plants.absorption import (
    PHOTON_ABSORPTION_METRICS_SCHEMA,
    PHOTON_ABSORPTION_SCAFFOLD_SCHEMA,
    PHOTON_ABSORPTION_SCHEMA_VERSION,
    LeafAbsorptionSurface,
    SurfacePhotonAbsorption,
    build_absorption_surface_registry,
    compute_photon_absorption_metrics,
    leaf_absorption_surfaces,
)
from rad_rebuild.radiance.engine.plants.artifacts import (
    PlantArtifactPaths,
    write_plant_artifacts,
)
from rad_rebuild.radiance.engine.plants.config import (
    PlantGeometryConfig,
    PlantOpticalAssumptions,
)
from rad_rebuild.radiance.engine.plants.generator import generate_plant_scene
from rad_rebuild.radiance.engine.plants.photosynthesis import (
    PLANT_PHOTOSYNTHESIS_RESPONSE_FILENAME,
    PLANT_PHOTOSYNTHESIS_RESPONSE_METHOD,
    PLANT_PHOTOSYNTHESIS_RESPONSE_SCHEMA,
    PhotosynthesisResponseParameters,
    build_plant_photosynthesis_response_payload,
    default_photosynthesis_response_parameters,
    photosynthetic_gross_rate_umol_co2_m2_s,
    photosynthetic_net_rate_umol_co2_m2_s,
    write_plant_photosynthesis_response_artifact,
)
from rad_rebuild.radiance.engine.plants.models import (
    LeafGeometry,
    LeafMesh,
    PlantGeometry,
    PlantScene,
)
from rad_rebuild.radiance.engine.plants.radiance_export import (
    export_scene_to_radiance,
)
from rad_rebuild.radiance.engine.plants.spectral import (
    SPECTRAL_ABSORPTION_METHOD,
    SPECTRAL_RESPONSE_SCHEMA,
    PLANT_SPECTRAL_RESPONSE_FILENAME,
    PLANT_SPECTRAL_RESPONSE_METHOD,
    PLANT_SPECTRAL_RESPONSE_SCHEMA,
    LeafSpectralOpticalBand,
    SpectralPhotonDistribution,
    SpectralPhotonFraction,
    build_leaf_spectral_absorption_summary,
    build_plant_spectral_response_payload,
    default_fixture_spectral_distribution,
    fixture_spectral_distribution_from_curve_data,
    parse_spectral_photon_fraction_overrides,
    write_plant_spectral_response_artifact,
    default_leafy_green_spectral_bands,
)
from rad_rebuild.radiance.engine.plants.surface_flux import (
    BASELINE_PPFD_PROXY_METHOD,
    SPATIAL_PPFD_PROXY_METHOD,
    RADIANCE_RECEIVER_METHOD,
    PLANT_SURFACE_FLUX_FILENAME,
    PLANT_SURFACE_FLUX_SCHEMA,
    build_baseline_proxy_surface_flux_rows,
    build_spatial_proxy_surface_flux_rows,
    build_radiance_receiver_samples,
    build_radiance_receiver_surface_flux_rows,
    build_plant_surface_flux_payload,
    parse_rtrace_receiver_output,
    read_ppfd_map_field,
    receiver_sample_input_text,
    write_baseline_proxy_plant_surface_flux_artifact,
    write_spatial_proxy_plant_surface_flux_artifact,
    write_radiance_receiver_plant_surface_flux_artifact,
)
from rad_rebuild.radiance.engine.plants.viewer_export import export_scene_to_viewer

__all__ = [
    "LeafAbsorptionSurface",
    "LeafGeometry",
    "LeafMesh",
    "PHOTON_ABSORPTION_METRICS_SCHEMA",
    "PHOTON_ABSORPTION_SCAFFOLD_SCHEMA",
    "PHOTON_ABSORPTION_SCHEMA_VERSION",
    "PLANT_PHOTOSYNTHESIS_RESPONSE_FILENAME",
    "PLANT_PHOTOSYNTHESIS_RESPONSE_METHOD",
    "PLANT_PHOTOSYNTHESIS_RESPONSE_SCHEMA",
    "PhotosynthesisResponseParameters",
    "build_plant_photosynthesis_response_payload",
    "default_photosynthesis_response_parameters",
    "photosynthetic_gross_rate_umol_co2_m2_s",
    "photosynthetic_net_rate_umol_co2_m2_s",
    "write_plant_photosynthesis_response_artifact",
    "PlantArtifactPaths",
    "PlantGeometry",
    "PlantGeometryConfig",
    "PlantOpticalAssumptions",
    "PLANT_SPECTRAL_RESPONSE_FILENAME",
    "PLANT_SPECTRAL_RESPONSE_METHOD",
    "PLANT_SPECTRAL_RESPONSE_SCHEMA",
    "build_plant_spectral_response_payload",
    "default_fixture_spectral_distribution",
    "fixture_spectral_distribution_from_curve_data",
    "parse_spectral_photon_fraction_overrides",
    "write_plant_spectral_response_artifact",
    "PLANT_SURFACE_FLUX_FILENAME",
    "PLANT_SURFACE_FLUX_SCHEMA",
    "PlantScene",
    "LeafSpectralOpticalBand",
    "SpectralPhotonDistribution",
    "SpectralPhotonFraction",
    "SPECTRAL_ABSORPTION_METHOD",
    "SPECTRAL_RESPONSE_SCHEMA",
    "build_leaf_spectral_absorption_summary",
    "default_leafy_green_spectral_bands",
    "SurfacePhotonAbsorption",
    "BASELINE_PPFD_PROXY_METHOD",
    "SPATIAL_PPFD_PROXY_METHOD",
    "RADIANCE_RECEIVER_METHOD",
    "build_absorption_surface_registry",
    "build_baseline_proxy_surface_flux_rows",
    "build_spatial_proxy_surface_flux_rows",
    "build_radiance_receiver_samples",
    "build_radiance_receiver_surface_flux_rows",
    "build_plant_surface_flux_payload",
    "parse_rtrace_receiver_output",
    "read_ppfd_map_field",
    "receiver_sample_input_text",
    "compute_photon_absorption_metrics",
    "export_scene_to_radiance",
    "export_scene_to_viewer",
    "generate_plant_scene",
    "leaf_absorption_surfaces",
    "write_baseline_proxy_plant_surface_flux_artifact",
    "write_spatial_proxy_plant_surface_flux_artifact",
    "write_radiance_receiver_plant_surface_flux_artifact",
    "write_plant_artifacts",
]
