"""Backend boundary model compatibility exports.

The canonical request, result, enum, and scalar contracts live in
`rad_rebuild.radiance.domain`. Backend modules import from this file for
historical compatibility, but there is only one model implementation.
"""

from __future__ import annotations

from rad_rebuild.radiance.domain import (
    DockerStatusResponse,
    ElectricalCostRequest,
    ElectricalCostStage,
    ElectricalEstimateResponse,
    ElectricalEstimateStageResponse,
    AssemblyAssetsResponse,
    AssemblyPhotometricBoundsResponse,
    AssemblyPhotometricColorScaleResponse,
    AssemblyPhotometricColormapResponse,
    AssemblyPhotometricLayerResponse,
    AssemblyPhotometricOrientationResponse,
    AssemblyInstanceResponse,
    AssemblyRoomResponse,
    AssemblySceneResponse,
    FiniteFixturePpfUmolS as FiniteFixturePpf,
    FiniteModulePowerW as FiniteModulePower,
    FiniteMountHeightM as FiniteMountHeight,
    FinitePositiveDimensionFt,
    FinitePpeUmolJ as FinitePpe,
    FiniteTargetPpfd,
    JobStatus,
    JobTailResponse,
    JsonObject,
    JsonValue,
    LayoutRequest,
    LayoutResponse,
    PublicErrorResponse,
    RadianceImagesResponse,
    RadianceManifestResponse,
    RadianceMetricsResponse,
    RadianceRunResponse,
    RadianceRunRequest,
    ReproduceResponse,
    RuntimeDockerModeStatusResponse,
    RuntimeLocalModeStatusResponse,
    RuntimeModesStatusResponse,
    RuntimePrecomputedModeStatusResponse,
    RuntimeSetupCommandResponse,
    RuntimeStatusResponse,
    StrictBoundaryModel,
    request_json_dict,
    request_with_updates,
)

__all__ = [
    "DockerStatusResponse",
    "ElectricalCostRequest",
    "ElectricalCostStage",
    "ElectricalEstimateResponse",
    "ElectricalEstimateStageResponse",
    "AssemblyAssetsResponse",
    "AssemblyPhotometricBoundsResponse",
    "AssemblyPhotometricColorScaleResponse",
    "AssemblyPhotometricColormapResponse",
    "AssemblyPhotometricLayerResponse",
    "AssemblyPhotometricOrientationResponse",
    "AssemblyInstanceResponse",
    "AssemblyRoomResponse",
    "AssemblySceneResponse",
    "FiniteFixturePpf",
    "FiniteModulePower",
    "FiniteMountHeight",
    "FinitePositiveDimensionFt",
    "FinitePpe",
    "FiniteTargetPpfd",
    "JobStatus",
    "JobTailResponse",
    "JsonObject",
    "JsonValue",
    "LayoutRequest",
    "LayoutResponse",
    "PublicErrorResponse",
    "RadianceImagesResponse",
    "RadianceManifestResponse",
    "RadianceMetricsResponse",
    "RadianceRunResponse",
    "RadianceRunRequest",
    "ReproduceResponse",
    "RuntimeDockerModeStatusResponse",
    "RuntimeLocalModeStatusResponse",
    "RuntimeModesStatusResponse",
    "RuntimePrecomputedModeStatusResponse",
    "RuntimeSetupCommandResponse",
    "RuntimeStatusResponse",
    "StrictBoundaryModel",
    "request_json_dict",
    "request_with_updates",
]
